# Generated by Django 4.2.2 on 2023-06-29 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='brief_info',
        ),
        migrations.AddField(
            model_name='article',
            name='date_of_event',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='sample description'),
        ),
        migrations.AddField(
            model_name='article',
            name='zoom_link',
            field=models.TextField(default='sample_link'),
        ),
    ]
